### PR TITLE
FIX [#642, RUM-3855]: Android Runtime Error in v2.3.1 for ReadableArray.asFirstPartyHosts()

### LINKED ISSUE #642: Android runtime error with v2.3.1
### Describe the bug

Android build runs successfully with React Native v0.72.10, but has this runtime error:

> java.util.HashMap cannot be cast to com.facebook.react.bridge.ReadableMap

error

iOS is unaffected.

### Reproduction steps

1. `npm run android`

### SDK logs

_No response_

### Expected behavior

Android app runs successfully.

### Affected SDK versions

2.3.1

### Latest working SDK version

2.2.0

### Did you confirm if the latest SDK version fixes the bug?

Yes

### Integration Methods

NPM

### React Native Version

0.72.10

### Package.json Contents

_No response_

### iOS Setup

_No response_

### Android Setup

_No response_

### Device Information

_No response_

### Other relevant information

_No response_

### PR DESCRIPTION
**Pull request by marco-saia-datadog**
### What does this PR do?

**ISSUE**: https://github.com/DataDog/dd-sdk-reactnative/issues/642

**INTRODUCED WITH:** v2.3.0 in PR https://github.com/DataDog/dd-sdk-reactnative/pull/625

Fixes a wrong cast which leads to a Runtime Error.

### Details

The tests rely on `JavaOnlyMap`, but its method `toHashMap` just wraps the map using a HashMap, without converting nested maps and arrays.

The `ReadableNativeMap`, which is the one used in a real use case, has a different implementation of `toHashMap` , which recursively converts the nested objects in either stdlib HashMap(s) or ArrayList(s).

The error shows up because `.asFirstPartyHosts()` performs an unsafe cast to `ReadableMap` for the nested objects inside of the array, but the actual type is `HashMap` from kotlin stdlib.

This PR introduces new conversion functions to ensure that the logic is consistent for different implementations of `ReadableArray` and `ReadableMap`.

### Review checklist (to be filled by reviewers)

- [x] Feature or bugfix MUST have appropriate tests
- [x] Make sure you discussed the feature or bugfix with the maintaining team in an Issue
- [x] Make sure each commit and the PR mention the Issue number (cf the [CONTRIBUTING](CONTRIBUTING.md) doc)

### CODE REVIEW

File: packages/core/android/src/main/kotlin/com/datadog/reactnative/DdSdkBridgeExt.kt [hunk 1]
```diff
@@ -47,3 +57,72 @@ internal fun Map<*, *>.toWritableMap(): WritableNativeMap {
...
+            else -> throw IllegalArgumentException("Could not convert object with key: $key.")
+        }
+    }
+
+    return hashMap
+}
+
+/**
+ * Recursively converts the ReadableArray to a ArrayList which only contains Kotlin stdlib objects,
+ * such as ArrayList, HashMap and the raw types.
```
Comment (0xnm) [inline packages/core/android/src/main/kotlin/com/datadog/reactnative/DdSdkBridgeExt.kt]: In Kotlin immutable interfaces are preferred, so it is better to use `List`, `Map`, etc. instead here

```suggestion
 * Recursively converts the ReadableArray to a [List] which only contains Kotlin stdlib objects,
 * such as [List], [Map] and the raw types.
```

File: packages/core/android/src/main/kotlin/com/datadog/reactnative/DdSdkBridgeExt.kt [hunk 2]
```diff
@@ -47,3 +57,72 @@ internal fun Map<*, *>.toWritableMap(): WritableNativeMap {
...
+ * @throws IllegalArgumentException if the readable array is malformed (eg. it contains a HashMap
```
Comment (0xnm) [inline packages/core/android/src/main/kotlin/com/datadog/reactnative/DdSdkBridgeExt.kt]: SDK shouldn't throw exceptions which will crash client application. Instead we should log an error and gracefully fallback (in this case probably ignoring item).

File: packages/core/android/src/main/kotlin/com/datadog/reactnative/DdSdkBridgeExt.kt [hunk 3]
```diff
@@ -47,3 +57,72 @@ internal fun Map<*, *>.toWritableMap(): WritableNativeMap {
...
+ * or ArrayList, instead of ReadableMap and ReadableArray respectively).
+ */
+internal fun ReadableArray.toKotlinArrayList(): ArrayList<*> {
```
Comment (0xnm) [inline packages/core/android/src/main/kotlin/com/datadog/reactnative/DdSdkBridgeExt.kt]: let's align with Kotlin stdlib lingvo

```suggestion
internal fun ReadableArray.toList(): List<*> {
```

File: packages/core/android/src/main/kotlin/com/datadog/reactnative/DdSdkBridgeExt.kt [hunk 4]
```diff
@@ -47,3 +57,72 @@ internal fun Map<*, *>.toWritableMap(): WritableNativeMap {
...
+    val arrayList = ArrayList<Any?>()
```
Comment (0xnm) [inline packages/core/android/src/main/kotlin/com/datadog/reactnative/DdSdkBridgeExt.kt]: It is better to use `mutableListOf` instead of concrete type. Also it makes little sense to store `null` values in the container, so type can be non-nullable.

```suggestion
    val result = mutableListOf<Any>()
```

File: packages/core/android/src/main/kotlin/com/datadog/reactnative/DdSdkBridgeExt.kt [hunk 5]
```diff
@@ -47,3 +57,72 @@ internal fun Map<*, *>.toWritableMap(): WritableNativeMap {
...
+    for (i in 0 until size()) {
+        // ReadableArray throws a null pointer exception if getMap(i) or getArray(i) returns null
```
Comment (0xnm) [inline packages/core/android/src/main/kotlin/com/datadog/reactnative/DdSdkBridgeExt.kt:181]: I don't see this documented, both methods are annotated as `NonNull` here https://github.com/facebook/react-native/blob/66634be13a37779bbafd75f24a88c97cf706cd2d/packages/react-native/ReactAndroid/src/main/java/com/facebook/react/bridge/ReadableArray.java#L34-L38.

In which case does it happen given that we check the type before calling these methods?

File: packages/core/android/src/main/kotlin/com/datadog/reactnative/DdSdkBridgeExt.kt [hunk 6]
```diff
@@ -47,3 +57,72 @@ internal fun Map<*, *>.toWritableMap(): WritableNativeMap {
...
+        @Suppress("TooGenericExceptionCaught")
+        try {
+            when (getType(i)) {
+                ReadableType.Null -> arrayList.add(null as Any?)
```
Comment (0xnm) [inline packages/core/android/src/main/kotlin/com/datadog/reactnative/DdSdkBridgeExt.kt]: I don't think it makes sense to add `null` to the container

```suggestion
                ReadableType.Null -> continue
```

File: packages/core/android/src/main/kotlin/com/datadog/reactnative/DdSdkBridgeExt.kt [hunk 7]
```diff
@@ -47,3 +57,72 @@ internal fun Map<*, *>.toWritableMap(): WritableNativeMap {
...
+                ReadableType.Boolean -> arrayList.add(getBoolean(i))
+                ReadableType.Number -> arrayList.add(getDouble(i))
+                ReadableType.String -> arrayList.add(getString(i))
+                ReadableType.Map -> arrayList.add(getMap(i).toKotlinHashMap())
+                ReadableType.Array -> arrayList.add(getArray(i).toKotlinArrayList())
+                else -> throw IllegalArgumentException("Unhandled ReadableType: $i.")
```
Comment (0xnm) [inline packages/core/android/src/main/kotlin/com/datadog/reactnative/DdSdkBridgeExt.kt]: we should log this case and also add it to the telemetry (in case if `ReadableType` enum gets new members in some new RN release, we should be aware).

File: packages/core/android/src/main/kotlin/com/datadog/reactnative/DdSdkBridgeExt.kt [hunk 8]
```diff
@@ -47,3 +57,72 @@ internal fun Map<*, *>.toWritableMap(): WritableNativeMap {
...
+                "Cannot convert ReadableArray to ArrayList of HashMap(s): " +
+                    "$it is not of type HashMap<*,*>",
+            )
+        }
+    }
+}
+
+/**
+ * Recursively converts the ReadableMap to a HashMap which only contains Kotlin stdlib objects,
+ * such as ArrayList, HashMap and the raw types.
```
Comment (0xnm) [inline packages/core/android/src/main/kotlin/com/datadog/reactnative/DdSdkBridgeExt.kt]: same explanation as before: we are interested in the immutable types and also not in the concrete implementations.

```suggestion
 * Recursively converts the [ReadableMap] to a [Map] which only contains Kotlin stdlib objects,
 * such as [List], [Map] and the raw types.
```

File: packages/core/android/src/main/kotlin/com/datadog/reactnative/DdSdkBridgeExt.kt [hunk 9]
```diff
@@ -47,3 +57,72 @@ internal fun Map<*, *>.toWritableMap(): WritableNativeMap {
...
+ * @throws IllegalArgumentException if the readable map is malformed (eg. it contains a HashMap
+ * or ArrayList, instead of ReadableMap and ReadableArray respectively).
+ */
```
Comment (0xnm) [inline packages/core/android/src/main/kotlin/com/datadog/reactnative/DdSdkBridgeExt.kt]: shouldn't throw, same explanation as before.

File: packages/core/android/src/main/kotlin/com/datadog/reactnative/DdSdkBridgeExt.kt [hunk 10]
```diff
@@ -47,3 +57,72 @@ internal fun Map<*, *>.toWritableMap(): WritableNativeMap {
...
+internal fun ReadableMap.toKotlinHashMap(): HashMap<String, Any> {
```
Comment (0xnm) [inline packages/core/android/src/main/kotlin/com/datadog/reactnative/DdSdkBridgeExt.kt]:
```suggestion
internal fun ReadableMap.toMap(): Map<String, Any> {
```

File: packages/core/android/src/main/kotlin/com/datadog/reactnative/DdSdkBridgeExt.kt [hunk 11]
```diff
@@ -47,3 +57,72 @@ internal fun Map<*, *>.toWritableMap(): WritableNativeMap {
...
+    val hashMap: HashMap<String, Any> = this.toHashMap()
```
Comment (0xnm) [inline packages/core/android/src/main/kotlin/com/datadog/reactnative/DdSdkBridgeExt.kt]: type is already clear from the call name

```suggestion
    val map = this.toHashMap()
```

File: packages/core/android/src/main/kotlin/com/datadog/reactnative/DdSdkBridgeExt.kt [hunk 12]
```diff
@@ -47,3 +57,72 @@ internal fun Map<*, *>.toWritableMap(): WritableNativeMap {
...
+    val iterator: Iterator<*> = hashMap.keys.iterator()
```
Comment (0xnm) [inline packages/core/android/src/main/kotlin/com/datadog/reactnative/DdSdkBridgeExt.kt]: Since the type of the map above is `<String, Any>`, iterator produced here should already have a type `Iterator<String>`. No need to widen the type and moreover specify it.

```suggestion
    val iterator = hashMap.keys.iterator()
```

File: packages/core/android/src/main/kotlin/com/datadog/reactnative/DdSdkBridgeExt.kt [hunk 13]
```diff
@@ -47,3 +57,72 @@ internal fun Map<*, *>.toWritableMap(): WritableNativeMap {
...
+
+    while (iterator.hasNext()) {
+        val key = iterator.next() as String
```
Comment (0xnm) [inline packages/core/android/src/main/kotlin/com/datadog/reactnative/DdSdkBridgeExt.kt]:
```suggestion
        val key = iterator.next()
```

File: packages/core/android/src/main/kotlin/com/datadog/reactnative/DdSdkBridgeExt.kt [hunk 14]
```diff
@@ -47,3 +57,72 @@ internal fun Map<*, *>.toWritableMap(): WritableNativeMap {
...
+        when (getType(key)) {
+            ReadableType.Null, ReadableType.Boolean, ReadableType.Number, ReadableType.String -> {}
```
Comment (0xnm) [inline packages/core/android/src/main/kotlin/com/datadog/reactnative/DdSdkBridgeExt.kt]: minor: just for clarity

```suggestion
            ReadableType.Null, ReadableType.Boolean, ReadableType.Number, ReadableType.String -> continue
```

File: packages/core/android/src/main/kotlin/com/datadog/reactnative/DdSdkBridgeExt.kt [hunk 15]
```diff
@@ -47,3 +57,72 @@ internal fun Map<*, *>.toWritableMap(): WritableNativeMap {
...
+            ReadableType.Map -> hashMap[key] = (Assertions.assertNotNull(getMap(key)) as ReadableMap).toKotlinHashMap()
+            ReadableType.Array -> hashMap[key] = (Assertions.assertNotNull(getArray(key)) as ReadableArray).toKotlinArrayList()
+            else -> throw IllegalArgumentException("Could not convert object with key: $key.")
```
Comment (0xnm) [inline packages/core/android/src/main/kotlin/com/datadog/reactnative/DdSdkBridgeExt.kt]: `Assertions` should be used only in tests and we cannot allow to throw anyway. So if `getType` returns map or array, why should it be other type in the value?

```suggestion
            ReadableType.Map -> hashMap[key] = getMap(key).toMap()
            ReadableType.Array -> hashMap[key] = getArray(key).toList()
            else -> { log to logcat and telemetry (if it is available) }
```

File: packages/core/android/src/main/kotlin/com/datadog/reactnative/DdSdkBridgeExt.kt [hunk 16]
```diff
@@ -47,3 +57,72 @@ internal fun Map<*, *>.toWritableMap(): WritableNativeMap {
     }
     return map
 }
+
+/**
+ * Casts the ReadableArray to a List that strictly contains non-null objects of type HashMap.
+ * @throws TypeCastException if at least one of the list items is not of type HashMap.
```
Comment (0xnm) [inline packages/core/android/src/main/kotlin/com/datadog/reactnative/DdSdkBridgeExt.kt]: shouldn't throw

File: packages/core/android/src/main/kotlin/com/datadog/reactnative/DdSdkBridgeExt.kt [hunk 17]
```diff
@@ -47,3 +57,72 @@ internal fun Map<*, *>.toWritableMap(): WritableNativeMap {
...
+ */
+internal fun ReadableArray.toHashMapArrayList(): List<HashMap<*, *>> {
```
Comment (0xnm) [inline packages/core/android/src/main/kotlin/com/datadog/reactnative/DdSdkBridgeExt.kt]: it seems there is only one call site of this, so maybe it is better write the necessary logic at the call site directly and remove this method.

File: packages/core/android/src/main/kotlin/com/datadog/reactnative/DdSdkConfigurationExt.kt [hunk 18]
```diff
@@ -94,12 +97,15 @@ internal fun ReadableMap.asProxyConfig(): Pair<Proxy, ProxyAuthenticator?>? {
 }
 
 internal fun ReadableArray.asFirstPartyHosts(): Map<String, Set<TracingHeaderType>> {
-    val firstPartyHosts = this.toArrayList() as List<ReadableMap>
-    return firstPartyHosts.mapNotNull<ReadableMap, JSONFirstPartyHost> {
-        val match = it.getString("match")
-        val propagatorTypes = it.getArray("propagatorTypes")
+    val firstPartyHosts = this.toHashMapArrayList()
```
Comment (0xnm) [inline packages/core/android/src/main/kotlin/com/datadog/reactnative/DdSdkConfigurationExt.kt]: I think this can be written this way.

```suggestion
    val firstPartyHosts = this.toList().filterIsInstance<ReadableMap>().toMap()
```

File: packages/core/android/src/main/kotlin/com/datadog/reactnative/DdSdkConfigurationExt.kt [hunk 19]
```diff
@@ -9,8 +9,11 @@ package com.datadog.reactnative
 
 import android.util.Log
 import com.datadog.android.trace.TracingHeaderType
+import com.facebook.infer.annotation.Assertions
```
Comment (0xnm) [inline packages/core/android/src/main/kotlin/com/datadog/reactnative/DdSdkConfigurationExt.kt]: unused import

File: packages/core/android/src/test/kotlin/com/datadog/reactnative/DdSdkBridgeExtTest.kt [hunk 20]
```diff
@@ -0,0 +1,292 @@
...
+ * Copyright 2016-Present Datadog, Inc.
+ */
+
+package com.datadog.reactnative
+
+import com.datadog.tools.unit.forge.BaseConfigurator
+import com.datadog.tools.unit.toReadableArray
+import com.datadog.tools.unit.toReadableMap
+import fr.xgouchet.elmyr.junit5.ForgeConfiguration
+import fr.xgouchet.elmyr.junit5.ForgeExtension
```
Comment (0xnm) [inline packages/core/android/src/test/kotlin/com/datadog/reactnative/DdSdkBridgeExtTest.kt]: Those are needed only if you are using https://github.com/xgouchet/Elmyr in your test class (and it seems you are not).

You can check the usage of the classes from this package in other test files.

File: packages/core/android/src/test/kotlin/com/datadog/reactnative/DdSdkBridgeExtTest.kt [hunk 21]
```diff
@@ -0,0 +1,292 @@
...
+                "number" to 1.23,
+                "string" to "test"
+            ).toReadableMap()
+
+        val hashMap = readableMap.toKotlinHashMap()
+
+        assert(hashMap["null"] == null)
+        assert(hashMap["boolean"] == true)
+        assert(hashMap["number"] == 1.23)
+        assert(hashMap["string"] == "test")
```
Comment (0xnm) [inline packages/core/android/src/test/kotlin/com/datadog/reactnative/DdSdkBridgeExtTest.kt]: these `assert` calls will always be good, because it is backed by https://docs.oracle.com/javase/8/docs/technotes/guides/language/assert.html.

They are no-op unless JVM started with `-ea` flag according to the documentation.

In tests we should be using `assertThat` instead, you can check in other files.

**Review by 0xnm — CHANGES_REQUESTED** [review]

File: packages/core/android/src/main/kotlin/com/datadog/reactnative/DdSdkBridgeExt.kt (hunk 5 above)
Comment (marco-saia-datadog) [reply packages/core/android/src/main/kotlin/com/datadog/reactnative/DdSdkBridgeExt.kt:181]: For `JavaOnlyArray` and `JavaOnlyMap`, if they contain stdlib objects, the case is not handled correctly. They can't return null, they throw a null pointer exception when trying to access the map or array, because they expect to find a `ReadableMap` or a `ReadableArray` respectively.

File: packages/core/android/src/main/kotlin/com/datadog/reactnative/DdSdkBridgeExt.kt (hunk 17 above)
Comment (marco-saia-datadog) [reply packages/core/android/src/main/kotlin/com/datadog/reactnative/DdSdkBridgeExt.kt]: I agree.

File: packages/core/android/src/main/kotlin/com/datadog/reactnative/DdSdkBridgeExt.kt (hunk 6 above)
Comment (marco-saia-datadog) [reply packages/core/android/src/main/kotlin/com/datadog/reactnative/DdSdkBridgeExt.kt]: I would keep it, as the original implementation of `toArrayList()` in ReadableNativeArray preserves null values.

File: packages/core/android/src/main/kotlin/com/datadog/reactnative/DdSdkBridgeExt.kt (hunk 5 above)
Comment (0xnm) [reply packages/core/android/src/main/kotlin/com/datadog/reactnative/DdSdkBridgeExt.kt:181]: How it is possible and where it happens? I'm checking the source code of `JavaOnlyArray`, for example.

Here, there is a cast https://github.com/facebook/react-native/blob/66634be13a37779bbafd75f24a88c97cf706cd2d/packages/react-native/ReactAndroid/src/main/java/com/facebook/react/bridge/JavaOnlyArray.java#L121 in the `getMap` call.

It should be no problem doing this cast and getting underlying value if `getType` call is made before, because `ReadableType.Map` [guarantees](https://github.com/facebook/react-native/blob/66634be13a37779bbafd75f24a88c97cf706cd2d/packages/react-native/ReactAndroid/src/main/java/com/facebook/react/bridge/JavaOnlyArray.java#L147) that there is indeed `ReadableMap` behind this index.

Comment (marco-saia-datadog) [reply packages/core/android/src/main/kotlin/com/datadog/reactnative/DdSdkBridgeExt.kt:181]: `getType` is (wrongly) annotated as `@NonNull` but it returns `null` whenever the object is not of type `ReadableMap` or `ReadableArray`.

It happens when you initialise the `JavaOnlyArray` with a `List` which contains instances of `Map` or `List` (or any other unhandled type).

The available constructors do not convert the nested objects, so they keep their original type, leading to this problem.

Here's the code for reference:

```java
  @Override
  public @NonNull ReadableType getType(int index) {
    Object object = mBackingList.get(index);

    if (object == null) {
      return ReadableType.Null;
    } else if (object instanceof Boolean) {
      return ReadableType.Boolean;
    } else if (object instanceof Double
        || object instanceof Float
        || object instanceof Integer
        || object instanceof Long) {
      return ReadableType.Number;
    } else if (object instanceof String) {
      return ReadableType.String;
    } else if (object instanceof ReadableArray) {
      return ReadableType.Array;
    } else if (object instanceof ReadableMap) {
      return ReadableType.Map;
    }
    return null;
  }
```

File: packages/core/android/src/main/kotlin/com/datadog/reactnative/DdSdkConfigurationExt.kt (hunk 18 above)
Comment (marco-saia-datadog) [reply packages/core/android/src/main/kotlin/com/datadog/reactnative/DdSdkConfigurationExt.kt]: I would keep `.toMapList()` implementation, previously called `.toHashMapArrayList()` so that we can log an error whenever object of unexpected types are found in the list.

File: packages/core/android/src/test/kotlin/com/datadog/reactnative/DdSdkBridgeExtTest.kt (hunk 20 above)
Comment (marco-saia-datadog) [reply packages/core/android/src/test/kotlin/com/datadog/reactnative/DdSdkBridgeExtTest.kt]: Correct, they came from using another class as a reference and I forgot to remove them!

File: packages/core/android/src/main/kotlin/com/datadog/reactnative/DdSdkBridgeExt.kt [hunk 22]
```diff
@@ -6,44 +6,187 @@
...
+            )
+            is Map<*, *> -> writableArray.pushMap(
+                it.toWritableMap(
+                    createWritableMap,
+                    createWritableArray
+                )
+            )
+            else -> Log.e(
+                javaClass.simpleName,
+                "Unhandled type ${it.javaClass.simpleName} has been ignored"
```
Comment (0xnm) [inline packages/core/android/src/main/kotlin/com/datadog/reactnative/DdSdkBridgeExt.kt]: minor: you probably want to be more precise here, because the message is the same as for `toWritableMap`, so if we get the report with such entry it won't be clear which place exactly logged it.

File: packages/core/android/src/main/kotlin/com/datadog/reactnative/DdSdkBridgeExt.kt [hunk 23]
```diff
@@ -6,44 +6,187 @@
...
-            is Long -> list.pushDouble(it.toDouble())
-            is Float -> list.pushDouble(it.toDouble())
-            is Double -> list.pushDouble(it)
-            is String -> list.pushString(it)
-            is List<*> -> list.pushArray(it.toWritableArray())
-            is Map<*, *> -> list.pushMap(it.toWritableMap())
-            else -> TODO()
+            null -> writableArray.pushNull()
+            is Int -> writableArray.pushInt(it)
+            is Long -> writableArray.pushDouble(it.toDouble())
```
Comment (0xnm) [inline packages/core/android/src/main/kotlin/com/datadog/reactnative/DdSdkBridgeExt.kt:43]: there is [pushLong](https://github.com/facebook/react-native/blob/ca5d940fe4f5540fb47319b690aa500feaabf710/packages/react-native/ReactAndroid/src/main/java/com/facebook/react/bridge/WritableArray.java#L23) method available, why do we use `pushDouble` here?

Ok, I see we used it even before [here](https://github.com/DataDog/dd-sdk-reactnative/pull/644/files#diff-226fa124b93e54b07eef11ff306c7bece15932cd4e3fc163e1a45735ce027271R98), but I'm curious if it is intentional or simply a bug.

File: packages/core/android/src/main/kotlin/com/datadog/reactnative/DdSdkBridgeExt.kt [hunk 24]
```diff
@@ -6,44 +6,187 @@
...
     return map
 }
+
+/**
+ * Recursively converts the [ReadableMap] to a [Map] which only contains Kotlin stdlib objects,
+ * such as [List], [Map] and the raw types.
+ */
+internal fun ReadableMap.toMap(): Map<String, Any> {
+    val map: HashMap<String, Any> = this.toHashMap()
+    val iterator: Iterator<String> = map.keys.iterator()
```
Comment (0xnm) [inline packages/core/android/src/main/kotlin/com/datadog/reactnative/DdSdkBridgeExt.kt]: minor: explicit types can be removed unless compiler infers them in a wrong way; they are not very useful

```suggestion
    val map = this.toHashMap()
    val iterator = map.keys.iterator()
```

File: packages/core/android/src/main/kotlin/com/datadog/reactnative/DdSdkBridgeExt.kt [hunk 25]
```diff
@@ -6,44 +6,187 @@
...
+                        javaClass.simpleName,
+                        "Cannot convert nested map for key: $key"
+                    )
+                }
+
+                ReadableType.Array -> {
+                    map[key] = getArray(key)?.toList() ?: Log.e(
+                        javaClass.simpleName,
+                        "Cannot convert nested array for key: $key"
+                    )
```
Comment (0xnm) [inline packages/core/android/src/main/kotlin/com/datadog/reactnative/DdSdkBridgeExt.kt]: I think that by using such expression `map[key] = whateverNullable ?: Log.e(...)` you will have `Unit` as a value for `map[key]` if `whateverNullable` is indeed `null` by some reason (if I'm not wrong).

We need either to re-write it to simple `if-else`, having:

```
val value = getMap(key)?.toMap()
if (value != null) { map[key] = value } else { Log.e(...) }  
```

File: packages/core/android/src/main/kotlin/com/datadog/reactnative/DdSdkBridgeExt.kt [hunk 26]
```diff
@@ -6,44 +6,187 @@
...
+    return map
+}
+
+/**
+ * Recursively converts the [ReadableArray] to a [List] which only contains Kotlin stdlib objects,
+ * such as [List], [Map] and the raw types.
+ * or [List], instead of [ReadableMap] and [ReadableArray] respectively).
+ */
+internal fun ReadableArray.toList(): List<*> {
+    val out = mutableListOf<Any?>()
```
Comment (0xnm) [inline packages/core/android/src/main/kotlin/com/datadog/reactnative/DdSdkBridgeExt.kt]: better to use non-nullable type here, because `null` values there are useless and it only widens the type (you need to handle null values) later when caller iterates over it.

Also it is better to rename it, because `out` is a reserved keyword in Kotlin (even here syntax highlighting treats it differently).

```suggestion
    val list = mutableListOf<Any>()
```

File: packages/core/android/src/main/kotlin/com/datadog/reactnative/DdSdkBridgeExt.kt [hunk 27]
```diff
@@ -6,44 +6,187 @@
...
+        try {
+            when (val type = getType(i)) {
+                ReadableType.Null -> out.add(null)
+                ReadableType.Boolean -> out.add(getBoolean(i))
+                ReadableType.Number -> out.add(getDouble(i))
+                ReadableType.String -> out.add(getString(i))
+                ReadableType.Map -> out.add(getMap(i).toMap())
+                ReadableType.Array -> out.add(getArray(i).toList())
+                else -> Log.e(javaClass.simpleName, "Unhandled ReadableType: ${type.name}.")
+            }
```
Comment (0xnm) [inline packages/core/android/src/main/kotlin/com/datadog/reactnative/DdSdkBridgeExt.kt]: a bit less code and non-nullable list

```suggestion
            val value = when (val type = getType(i)) {
                ReadableType.Null -> null
                ReadableType.Boolean -> getBoolean(i)
                ReadableType.Number -> getDouble(i)
                ReadableType.String -> getString(i)
                ReadableType.Map -> getMap(i).toMap()
                ReadableType.Array -> getArray(i).toList()
                else -> {
                  Log.e(javaClass.simpleName, "Unhandled ReadableType: ${type.name}.")
                  null
                }
            }
            if (value != null) list += value
```

File: packages/core/android/src/main/kotlin/com/datadog/reactnative/DdSdkConfigurationExt.kt [hunk 28]
```diff
@@ -94,13 +95,27 @@ internal fun ReadableMap.asProxyConfig(): Pair<Proxy, ProxyAuthenticator?>? {
...
-    return firstPartyHosts.mapNotNull<ReadableMap, JSONFirstPartyHost> {
-        val match = it.getString("match")
-        val propagatorTypes = it.getArray("propagatorTypes")
-        if (match != null && propagatorTypes != null) {
-            JSONFirstPartyHost(match, propagatorTypes.toArrayList() as List<String>)
-        } else null
+    return this.toList().mapNotNull {
+        if (it == null) {
+            null
+        } else if (it !is Map<*, *>) {
```
Comment (0xnm) [inline packages/core/android/src/main/kotlin/com/datadog/reactnative/DdSdkConfigurationExt.kt:101]: `mapNotNull` already guarantees that argument is not `null`

```suggestion
    return this.toList().mapNotNull {
        if (it !is Map<*, *>) {
```

File: packages/core/android/src/test/kotlin/com/datadog/reactnative/DdSdkBridgeExtTest.kt [hunk 29]
```diff
@@ -0,0 +1,361 @@
...
+        3.0f,
+        "double",
+        4.0,
+        "string",
+        "test",
+        "boolean",
+        true
+    )
+
+    // Long type is not handled in JavaOnlyArray getType() in RN 0.71.10
```
Comment (0xnm) [inline packages/core/android/src/test/kotlin/com/datadog/reactnative/DdSdkBridgeExtTest.kt:271]: ah, that is why `putDouble` instead of `putLong`?

File: packages/core/android/src/test/kotlin/com/datadog/reactnative/DdSdkBridgeExtTest.kt [hunk 30]
```diff
@@ -0,0 +1,361 @@
...
+
+@Extensions(ExtendWith(MockitoExtension::class))
+@MockitoSettings(strictness = Strictness.LENIENT)
+internal class DdSdkBridgeExtTest {
+    // Default providers for toWritableArray and toWritableMap
+    private val createWritableMap = { JavaOnlyMap() }
+    private val createWritableArray = { JavaOnlyArray() }
+
+    @Test
+    fun `M call toWritableArray W all types of supported values`() {
```
Comment (0xnm) [inline packages/core/android/src/test/kotlin/com/datadog/reactnative/DdSdkBridgeExtTest.kt]: Normally for Android/Kotlin we follow the format: M - must; designates expected outcome in the assertions; W - when; designates the call made; {} - optional condition.

also very minor: we also tend to split test into `Given/When/Then` blocks for readability

```suggestion
    fun `M do a proper conversion W toWritableArray { all types of supported values }`() {
```

File: packages/core/android/src/test/kotlin/com/datadog/reactnative/DdSdkBridgeExtTest.kt [hunk 31]
```diff
@@ -0,0 +1,361 @@
...
+        val writableArray = array.toWritableArray(createWritableMap, createWritableArray)
+
+        assertDoesNotThrow {
+            assertThat(writableArray.size()).isEqualTo(array.size)
+            testWritableArray(writableArray)
+
+            // Nested map
+            val nestedMap = writableArray.getMap(array.size - 2)
+            assertThat(nestedMap).isInstanceOf(WritableMap::class.java)
+            assertThat(nestedMap.keys().size).isEqualTo(nestedTestMap.keys.size)
```
Comment (0xnm) [inline packages/core/android/src/test/kotlin/com/datadog/reactnative/DdSdkBridgeExtTest.kt]: you will have more descriptive message. same applies to similar assertions in other tests below.

```suggestion
            assertThat(nestedMap.keys()).hasSize(nestedTestMap.keys.size)
```

File: packages/core/android/src/test/kotlin/com/datadog/reactnative/DdSdkBridgeExtTest.kt [hunk 32]
```diff
@@ -0,0 +1,361 @@
...
+    fun `M call toWritableArray W all types of supported values`() {
+        val array = getTestArray()
+        val nestedTestMap = getTestMap()
+        val nestedTestArray = getTestArray()
+        array.add(nestedTestMap) // Nested map
+        array.add(nestedTestArray) // Nested array
+
+        val writableArray = array.toWritableArray(createWritableMap, createWritableArray)
+
+        assertDoesNotThrow {
```
Comment (0xnm) [inline packages/core/android/src/test/kotlin/com/datadog/reactnative/DdSdkBridgeExtTest.kt]: imo this can be removed, because `assertDoesNotThrow` doesn't specify the exception type, message, etc. If something will be thrown you will see exception in the test results anyway and test will fail as well.

But not pushing for it.

File: packages/core/android/src/main/kotlin/com/datadog/reactnative/DdSdkBridgeExt.kt (hunk 22 above)
Comment (marco-saia-datadog) [reply packages/core/android/src/main/kotlin/com/datadog/reactnative/DdSdkBridgeExt.kt]: Good catch

File: packages/core/android/src/main/kotlin/com/datadog/reactnative/DdSdkBridgeExt.kt (hunk 6 above)
Comment (0xnm) [reply packages/core/android/src/main/kotlin/com/datadog/reactnative/DdSdkBridgeExt.kt]: not sure why RN team have `null` values there. Maybe just for the case when their lists have key-pairs, like `listOf("a", null, "b", 2)`. But this is very strange usage and I guess for us we don't receive such structures?

File: packages/core/android/src/main/kotlin/com/datadog/reactnative/DdSdkBridgeExt.kt (hunk 5 above)
Comment (0xnm) [reply packages/core/android/src/main/kotlin/com/datadog/reactnative/DdSdkBridgeExt.kt:181]: okay, signature is lying then. clear enough

File: packages/core/android/src/main/kotlin/com/datadog/reactnative/DdSdkBridgeExt.kt (hunk 23 above)
Comment (marco-saia-datadog) [reply packages/core/android/src/main/kotlin/com/datadog/reactnative/DdSdkBridgeExt.kt:43]: Long values are not handled in RN 0.71.10, and have been introduced recently with this PR: https://github.com/facebook/react-native/commit/0dc5c5f1f43701f396d2eb49bbabd2bfd2338cf4 

Using long values elsewhere (eg. initialising a writable array or map containing a long value somewhere) might also lead to a crash due to this:

https://github.com/facebook/react-native/pull/43158

File: packages/core/android/src/main/kotlin/com/datadog/reactnative/DdSdkBridgeExt.kt (hunk 26 above)
Comment (marco-saia-datadog) [reply packages/core/android/src/main/kotlin/com/datadog/reactnative/DdSdkBridgeExt.kt]: I am supporting null values because ReadableArrays support them, and I wanted to provide a method to do a 1:1 conversion. What do you think?

I agree I should rename the variable.

File: packages/core/android/src/main/kotlin/com/datadog/reactnative/DdSdkConfigurationExt.kt (hunk 28 above)
Comment (marco-saia-datadog) [reply packages/core/android/src/main/kotlin/com/datadog/reactnative/DdSdkConfigurationExt.kt:101]: `mapNotNull` only guarantees that the resulting list will not contain any null values, but the argument can be null, and when it is I want to skip it, so I return null.

File: packages/core/android/src/test/kotlin/com/datadog/reactnative/DdSdkBridgeExtTest.kt (hunk 29 above)
Comment (marco-saia-datadog) [reply packages/core/android/src/test/kotlin/com/datadog/reactnative/DdSdkBridgeExtTest.kt:271]: Partially. See the comment above.

File: packages/core/android/src/main/kotlin/com/datadog/reactnative/DdSdkBridgeExt.kt (hunk 26 above)
Comment (0xnm) [reply packages/core/android/src/main/kotlin/com/datadog/reactnative/DdSdkBridgeExt.kt]: well, down the line you are calling `mapNotNull` anyway and as I replied here https://github.com/DataDog/dd-sdk-reactnative/pull/644#discussion_r1549869773 probably the only reason `null` is supported in `ReadableArray` this weird use-case when it is used like a map and they need to keep structural ordering.

But I'm fine with keeping it as `<Any?>`, just wanted to simplify it a bit (and having `null` values in the list is not quite idiomatic in Java/Kotlin, it makes little sense).

File: packages/core/android/src/main/kotlin/com/datadog/reactnative/DdSdkConfigurationExt.kt (hunk 28 above)
Comment (0xnm) [reply packages/core/android/src/main/kotlin/com/datadog/reactnative/DdSdkConfigurationExt.kt:101]: indeed, I'm wrong here, ignore my comment then. Alternatively you can call `filterNotNull` btw to avoid having this check.

File: packages/core/android/src/main/kotlin/com/datadog/reactnative/DdSdkBridgeExt.kt (hunk 25 above)
Comment (0xnm) [reply packages/core/android/src/main/kotlin/com/datadog/reactnative/DdSdkBridgeExt.kt]: indeed, it will be `Unit` in the `map[key]` in such scenario: link to reproduce https://pl.kotl.in/b54hT6ggk

Comment (marco-saia-datadog) [reply packages/core/android/src/main/kotlin/com/datadog/reactnative/DdSdkBridgeExt.kt]: Yes, that's a clear mistake on my side! Thank you

File: packages/core/android/src/main/kotlin/com/datadog/reactnative/DdSdkBridgeExt.kt (hunk 26 above)
Comment (marco-saia-datadog) [reply packages/core/android/src/main/kotlin/com/datadog/reactnative/DdSdkBridgeExt.kt]: At the moment `mapNotNull` is used in one specific use-case (`asFirstPartyHosts()`), but the extension method is generic and it will surely be used many times in the future.

I agree that in 99% of real use cases, having null values makes little sense.

On the other hand, if for some reason I want to return 3 arguments from Kotlin to the RN side, and I want them to be nullable and keep their position in the array, I'd have a list like this:

```kotlin
val args = listOf(null, "arg2", "arg3")
```

And I would convert it to a `WritableArray`, expecting to find the elements in the same position, so I'd call `args.toWritableArray()` and get a perfect match.

On the other hand, if I am aware my list can contain null values, and I want to remove them, then I'd call `args.mapNotNull().toWritableArray()`.

I think this way we ultimately leave the choice to the developer.

File: packages/core/android/src/test/kotlin/com/datadog/reactnative/DdSdkBridgeExtTest.kt [hunk 33]
```diff
@@ -0,0 +1,382 @@
...
+            1,
+            2.0f,
+            3.0,
+            "test",
+            true
+        )
+    )
+
+    private fun testWritableArray(array: WritableArray) {
+        assertThat(array.getDynamic(0).isNull).isEqualTo(true)
```
Comment (0xnm) [inline packages/core/android/src/test/kotlin/com/datadog/reactnative/DdSdkBridgeExtTest.kt]:
```suggestion
        assertThat(array.getDynamic(0).isNull).isTrue
```

File: packages/core/android/src/test/kotlin/com/datadog/reactnative/DdSdkBridgeExtTest.kt [hunk 34]
```diff
@@ -0,0 +1,382 @@
...
+        assertThat(array.getDouble(2)).isEqualTo(2.0)
+
+        assertThat(array.getDouble(3)).isInstanceOf(java.lang.Double::class.java)
+        assertThat(array.getDouble(3)).isEqualTo(3.0)
+
+        assertThat(array.getString(4)).isInstanceOf(java.lang.String::class.java)
+        assertThat(array.getString(4)).isEqualTo("test")
+
+        assertThat(array.getBoolean(5)).isInstanceOf(java.lang.Boolean::class.java)
+        assertThat(array.getBoolean(5)).isEqualTo(true)
```
Comment (0xnm) [inline packages/core/android/src/test/kotlin/com/datadog/reactnative/DdSdkBridgeExtTest.kt]:
```suggestion
        assertThat(array.getBoolean(5)).isTrue
```

same changes apply below

**Review by 0xnm — DISMISSED** [review]
lgtm! I hope that we add also integration test to check full configuration conversion through the layers.

**Review by 0xnm — APPROVED** [review]
