### PR TITLE
Make sure Datadog SDK is initialized on the main thread. Fixes #198

### LINKED ISSUE #198: iOS: UI API called from background thread - UIApplication.applicationState must be used from main thread only
**Describe what happened**
```
UI API called from background thread
file://<app_path>/ios/Pods/DatadogSDK/Sources/Datadog/Core/System/AppStateListener.swift: runtime: UI API called from background thread: UIApplication.applicationState must be used from main thread only

Thread 25
#0	0x0000000102abcea3 in AppStateListener.__allocating_init(dateProvider:) at <app_path>/ios/Pods/DatadogSDK/Sources/Datadog/Core/System/AppStateListener.swift:155
#1	0x0000000102b126b9 in static Datadog.initializeOrThrow(initialTrackingConsent:configuration:) at <app_path>/ios/Pods/DatadogSDK/Sources/Datadog/Datadog.swift:230
#2	0x0000000102b10875 in static Datadog.initialize(appContext:trackingConsent:configuration:) at <app_path>/ios/Pods/DatadogSDK/Sources/Datadog/Datadog.swift:84
#3	0x0000000102d1edfa in DdSdkImplementation.initialize(configuration:) at <app_path>/ios/Pods/DatadogSDKBridge/DatadogSDKBridge/Classes/Implementation/DdSdkImplementation.swift:16
#4	0x0000000102d1eec3 in @objc DdSdkImplementation.initialize(configuration:) ()
#5	0x0000000102d27e67 in RNDdSdk.initialize(configuration:resolve:reject:) at <app_path>/node_modules/@datadog/mobile-react-native/ios/Sources/DdSdk.swift:25
#6	0x0000000102d27f3c in @objc RNDdSdk.initialize(configuration:resolve:reject:) ()
#7	0x0000000115e58fdb in __invoking___ ()
#8	0x0000000115e5634e in -[NSInvocation invoke] ()
#9	0x0000000115e565e1 in -[NSInvocation invokeWithTarget:] ()
#10	0x000000010342d3f5 in -[RCTModuleMethod invokeWithBridge:module:arguments:] at <app_path>/node_modules/react-native/React/Base/RCTModuleMethod.mm:584
#11	0x0000000103431889 in facebook::react::invokeInner(RCTBridge*, RCTModuleData*, unsigned int, folly::dynamic const&, int, (anonymous namespace)::SchedulingContext) at <app_path>/node_modules/react-native/React/CxxModule/RCTNativeModule.mm:183
#12	0x000000010343113b in facebook::react::RCTNativeModule::invoke(unsigned int, folly::dynamic&&, int)::$_0::operator()() const at <app_path>/node_modules/react-native/React/CxxModule/RCTNativeModule.mm:104
#13	0x0000000103431098 in invocation function for block in facebook::react::RCTNativeModule::invoke(unsigned int, folly::dynamic&&, int) at <app_path>/node_modules/react-native/React/CxxModule/RCTNativeModule.mm:95
#14	0x00000001229b0815 in _dispatch_call_block_and_release ()
#15	0x00000001229b1a5a in _dispatch_client_callout ()
#16	0x00000001229b83bc in _dispatch_lane_serial_drain ()
#17	0x00000001229b90ec in _dispatch_lane_invoke ()
#18	0x00000001229c5600 in _dispatch_workloop_worker_thread ()
#19	0x0000000122bc9fcf in _pthread_wqthread ()
#20	0x0000000122bc8f56 in start_wqthread ()
```

**Steps to reproduce the issue:**
Launch application and initialize datadog

**Describe what you expected:**
No runtime warning

**Additional context**
    - Version of the SDK: `1.0.0-rc7`

### PR DESCRIPTION
**Pull request by cltnschlosser**
### What does this PR do?

Makes sure the the Datadog SDK is initialized on the main thread

### Motivation

 Fixes #198

### Review checklist (to be filled by reviewers)

- [ ] Feature or bugfix MUST have appropriate tests ()
- [ ] Make sure you discussed the feature or bugfix with the maintaining team in an Issue
- [x] Make sure each commit and the PR mention the Issue number (cf the [CONTRIBUTING](CONTRIBUTING.md) doc)
- [x] If this PR is auto-generated, please make sure also to manually update the code related to the change

### CODE REVIEW

**Review by xgouchet — APPROVED** [review]
LGTM, waiting for additional reviews

**Review by mariusc83 — APPROVED** [review]

File: packages/core/ios/Sources/DdSdk.swift [hunk 1]
```diff
@@ -22,7 +22,16 @@ class RNDdSdk: NSObject {
...
+        // This is safe because the main queue will never be blocked waiting for the sharedQueue
+        // Adding an extra check in case sharedQueue is ever changed to be DispatchQueue.main.
+        if Thread.isMainThread {
+            nativeInstance.initialize(configuration: configuration.asDdSdkConfiguration())
+        } else {
+            DispatchQueue.main.sync {
+                nativeInstance.initialize(configuration: configuration.asDdSdkConfiguration())
+            }
+        }
         resolve(nil)
```
Comment (maxep) [inline packages/core/ios/Sources/DdSdk.swift:35]: The extra check is required to avoid deadlock, I'm not familiar with RN threading but since the method signature has callbacks it seems safer to do an `async` dispatch here:
```suggestion
       DispatchQueue.main.async {
          nativeInstance.initialize(configuration: configuration.asDdSdkConfiguration())
          resolve(nil)
      }
```

Would that work?

File: packages/core/ios/Sources/DdSdk.swift [hunk 2]
```diff
@@ -22,7 +22,16 @@ class RNDdSdk: NSObject {
...
     }
```
Comment (maxep) [inline packages/core/ios/Sources/DdSdk.swift:36]: The extra check is required to avoid deadlock, I'm not familiar with RN threading but since the method signature has callbacks it seems safer to do an `async` dispatch here:
```suggestion
@objc(initialize:withResolver:withRejecter:)
func initialize(configuration: NSDictionary, resolve: @escaping RCTPromiseResolveBlock, reject: @escaping RCTPromiseRejectBlock) -> Void {
    DispatchQueue.main.async {
        self.nativeInstance.initialize(configuration: configuration.asDdSdkConfiguration())
        resolve(nil)
    }
}
```

Would that work?

Comment (cltnschlosser) [reply packages/core/ios/Sources/DdSdk.swift:36]: Yeah, should be totally fine. I didn’t sync to keep the sharedQueue busy, but it’s unlikely any other work would happen in parallel to this.

The extra check is unneeded today, but if a developer ever changed the sharedQueue to DispatchQueue.main then it prevents the deadlock in that case.
